# Generated by Django 3.0.5 on 2020-07-09 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_pulblished',
            new_name='is_published',
        ),
    ]
